using Xunit;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 2016-03-20 23:32:09Z
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NickBuhro.Tests
{
	partial class TransliterationTests
	{
		[Fact]
		public void RussianToLatinTest01()
		{
			var cyrillic = @"1";
			var latin = @"1";
			RussianToLatinTestHelper(cyrillic, latin);
		}

		[Fact]
		public void LatinToRussianTest01()
		{
			var cyrillic = @"1";
			var latin = @"1";
			LatinToRussianTestHelper(latin, cyrillic);
		}

		[Fact]
		public void RussianToLatinTest02()
		{
			var cyrillic = @"в";
			var latin = @"v";
			RussianToLatinTestHelper(cyrillic, latin);
		}

		[Fact]
		public void LatinToRussianTest02()
		{
			var cyrillic = @"в";
			var latin = @"v";
			LatinToRussianTestHelper(latin, cyrillic);
		}

		[Fact]
		public void RussianToLatinTest03()
		{
			var cyrillic = @"В";
			var latin = @"V";
			RussianToLatinTestHelper(cyrillic, latin);
		}

		[Fact]
		public void LatinToRussianTest03()
		{
			var cyrillic = @"В";
			var latin = @"V";
			LatinToRussianTestHelper(latin, cyrillic);
		}

		[Fact]
		public void RussianToLatinTest04()
		{
			var cyrillic = @"ж";
			var latin = @"zh";
			RussianToLatinTestHelper(cyrillic, latin);
		}

		[Fact]
		public void LatinToRussianTest04()
		{
			var cyrillic = @"ж";
			var latin = @"zh";
			LatinToRussianTestHelper(latin, cyrillic);
		}

		[Fact]
		public void RussianToLatinTest05()
		{
			var cyrillic = @"щ";
			var latin = @"shh";
			RussianToLatinTestHelper(cyrillic, latin);
		}

		[Fact]
		public void LatinToRussianTest05()
		{
			var cyrillic = @"щ";
			var latin = @"shh";
			LatinToRussianTestHelper(latin, cyrillic);
		}

		[Fact]
		public void RussianToLatinTest06()
		{
			var cyrillic = @"Все люди рождаются свободными и равными в своём достоинстве и правах.";
			var latin = @"Vse lyudi rozhdayutsya svobodnymi i ravnymi v svoyom dostoinstve i pravakh.";
			RussianToLatinTestHelper(cyrillic, latin);
		}

		[Fact]
		public void LatinToRussianTest06()
		{
			var cyrillic = @"Все люди рождаются свободными и равными в своём достоинстве и правах.";
			var latin = @"Vse lyudi rozhdayutsya svobodnymi i ravnymi v svoyom dostoinstve i pravakh.";
			LatinToRussianTestHelper(latin, cyrillic);
		}

		[Fact]
		public void RussianToLatinTest07()
		{
			var cyrillic = @"Они наделены разумом и совестью и должны поступать в отношении друг друга в духе братства.";
			var latin = @"Oni nadeleny razumom i sovestyu i dolzhny postupat v otnoshenii drug druga v dukhe bratstva.";
			RussianToLatinTestHelper(cyrillic, latin);
		}

		[Fact]
		public void LatinToRussianTest07()
		{
			var cyrillic = @"Они наделены разумом и совестью и должны поступать в отношении друг друга в духе братства.";
			var latin = @"Oni nadeleny razumom i sovestyu i dolzhny postupat v otnoshenii drug druga v dukhe bratstva.";
			LatinToRussianTestHelper(latin, cyrillic);
		}

	}
}

